############################
## CHANGE THESE
############################

baseURL: "https://gujarats.github.io/blog/"
title: "My Blog"

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true

