############################
## Author
############################

author:
  name: "Gujarat Santana"
  image: author.png
  greeting: "A personal blog theme for Hugo :evergreen_tree:"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/gujarats

###############################
## OpenGraph & Twitter Cards
###############################

title: "Tech Blog"
description: "My Personal Tech Blog"
images:
  - thumbnail.png
