# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

baseurl = "http://hugo.spf13.com/"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
canonifyurls = true
paginate = 3
theme = "code-editor"

[params]
    author = "John Doe"
    locale = "en-US"
